controllers/BlogController.php
<?php

namespace app\controllers;

use app\modules\Post\models\Post;
use Yii;
use app\modules\Post\models\PostSearch;


class BlogController extends FrontController
{


    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionPost($id)
    {
        $post = Post::find()->where(['ID'=>$id])->with('lang')->one();
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('singlePost', [
            'post' => $post,
            'dataProvider' => $dataProvider,
        ]);
    }
}

views/themes/shop617/blog/_post_item_down.php
<?php
use yii\bootstrap\Html;

?>
<div class="col-md-4" data-mh="11">
    <div class="blog-box">
        <a href="<?=\yii\helpers\Url::to(['/blog/post','id'=>$model->ID])?>">

            <div class="info">
                <div class="small-title">
                    <?=$model->lang->Title?>
                </div>
                <div class="date-post">
                    <?=$model->niceDate?>
                </div>
                <div class="description">
                    <?=$model->shortContent?>
                </div>
            </div>
            <div class="img">
                <?= Html::img($model->mainImage->imagePath, ['width' => 550, 'class' => 'img-responsive']) ?>
            </div>
        </a>
    </div>
</div>

views/themes/shop617/blog/_post_item_up.php
<?php
use yii\bootstrap\Html;
?>
<div class="col-md-4" data-mh="11">
    <div class="blog-box">
        <a href="<?=\yii\helpers\Url::to(['/blog/post','id'=>$model->ID])?>">
            <div class="img">
                <?= Html::img($model->mainImage->imagePath, ['width' => 550, 'class' => 'img-responsive']) ?>
            </div>
            <div class="info">
                <div class="small-title">
                    <?=$model->lang->Title?>
                </div>
                <div class="date-post">
                    <?=$model->niceDate?>
                </div>
                <div class="description">
                    <?=$model->shortContent?>
                </div>
            </div>
        </a>
    </div>
</div>

views/themes/shop617/blog/index.php
<?php

use app\views\themes\shop617\assets\FrontAsset;
use yii\widgets\ListView;

$bundle = FrontAsset::register($this);
?>

<section class="name-page">
    <div class="container">
        <div class="big-title">
            Blog
        </div>
    </div>
</section>

<section class="blog different">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/home">Acasa</a></li>
            <li class="breadcrumb-item active">BLOG</li>
        </ol>
        <div class="row">
            <?=
            ListView::widget([
                'dataProvider' => $dataProvider,
                'layout' => "{summary}\n{items}\n<span class='clearfix'></span><div class='pull-right'>{pager}</div>\n",
                'itemView' => function ($model, $key,$index) {
                    if ($index % 2 == 0) {
                        return $this->render('_post_item_up', ['model' => $model]);
                    } else {
                        return $this->render('_post_item_down', ['model' => $model]);
                    }
                }
            ]);
            ?>


        </div>
<!--        <div class="text-right">-->
<!--            <nav aria-label="Page navigation">-->
<!--                <ul class="pagination">-->
<!--                    <li>-->
<!--                        <a href="#" aria-label="Previous">-->
<!--                            <span aria-hidden="true">&laquo;</span>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li class="active"><a href="#">1</a></li>-->
<!--                    <li><a href="#">2</a></li>-->
<!--                    <li><a href="#">3</a></li>-->
<!--                    <li><a href="#">4</a></li>-->
<!--                    <li><a href="#">5</a></li>-->
<!--                    <li>-->
<!--                        <a href="#" aria-label="Next">-->
<!--                            <span aria-hidden="true">&raquo;</span>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </nav>-->
<!--        </div>-->
    </div>
</section>

views/themes/shop617/blog/singlePost.php
<?php
use app\views\themes\shop617\assets\FrontAsset;
use yii\helpers\Html;
use yii\widgets\ListView;

$bundle = FrontAsset::register($this);

?>

<section class="name-page">
    <div class="container">
        <div class="big-title">
            Blog
        </div>
    </div>
</section>

<section class="post">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Acasa</a></li>
            <li class="breadcrumb-item"><a href="/blog">Blog</a></li>
            <li class="breadcrumb-item active"><?=$post->lang->Title?></li>
        </ol>
        <div class="about-post">
            <div class="row">
                <div class="col-md-5">
                    <div class="img-box">
                        <?= Html::img($post->mainImage->imagePath, ['width' => 550, 'class' => 'img-responsive']) ?>
                    </div>
                </div>
                <div class="info-product">
                    <div class="big-different-title">
                        <?=$post->lang->Title?>
                    </div>
                </div>
                    <?=$post->lang->Content?>

            </div>
        </div>
    </div>
</section>

<section class="blog different">
    <div class="container">
        <div class="text-left">
            <div class="title">
                Alte bloguri
            </div>
        </div>
        <div class="row">
            <?=
            ListView::widget([
                'dataProvider' => $dataProvider,
                'layout' => "{items}\n<span class='clearfix'></span><div class='pull-right'>{pager}</div>\n",
                'itemView' => function ($model, $key,$index) {
                    if ($index % 2 == 0) {
                        return $this->render('_post_item_up', ['model' => $model]);
                    } else {
                        return $this->render('_post_item_down', ['model' => $model]);
                    }
                }
            ]);
            ?>
        </div>
    </div>
</section>